query factionTopPlayers($factionId: Int!, $numPlayers: Int!) {
  playersByWins(first: $numPlayers, factionId: $factionId) {
    edges {
      node {
        id
        displayName
        steamId
        totalWins
        totalMatches
      }
    }
  }
}
