query factionStats($numTopPlayers: Int!) {
  factions {
    id
    name
    totalWins
    totalMatches
    topPlayers(first: $numTopPlayers) {
      player {
        id
        displayName
        steamId
      }
      totalWins
    }
    statsByPlayerCount {
      playerCount
      totalWins
      totalMatches
    }
    factionMatCombos {
      playerMat {
        id
        name
      }
      totalWins
      totalMatches
      avgCoinsOnWin
      avgRoundsOnWin
      leastRoundsForWin
    }
  }
}
