query factionStats($factionId: Int!, $numPlayers: Int!) {
  faction(id: $factionId) {
    id
    name
    totalWins
    totalMatches
    statsByPlayerCount {
      playerCount
      totalWins
      totalMatches
    }
  }
  factionMatCombos(factionId: $factionId) {
    playerMat {
      id
      name
    }
    totalWins
    totalMatches
    avgCoinsOnWin
    avgRoundsOnWin
    leastRoundsForWin
  }
  playersByWins(first: $numPlayers, factionId: $factionId) {
    edges {
      node {
        id
        displayName
        steamId
        totalWins(factionId: $factionId)
        totalMatches(factionId: $factionId)
      }
    }
  }
}
