query factionStats {
  factions {
    id
    name
    statsByPlayerCount {
      playerCount
      totalWins
      totalMatches
    }
    factionMatCombos {
      playerMat {
        id
        name
      }
      statsByPlayerCount {
        playerCount
        totalWins
        totalMatches
        avgCoinsOnWin
        avgRoundsOnWin
        leastRoundsForWin
      }
    }
  }
}
