# import PlayerMatchResult from "../fragments/player-match-result.gql"

query matches($first: Int!, $after: String) {
  matches(first: $first, after: $after) {
    edges {
      node {
        id
        datePlayed
        numRounds
        playerMatchResults {
          ...PlayerMatchResult
        }
        winner {
          id
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
