query matches($first: Int!, $after: String) {
  matches(first: $first, after: $after) {
    edges {
      node {
        id
        datePlayed
        numRounds
        playerMatchResults {
          id
          player {
            id
            displayName
            steamId
          }
          faction {
            id
            name
          }
          playerMat {
            id
            name
          }
          coins
          tieOrder
        }
        winner {
          id
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
