query tiers($numTopPlayers: Int!) {
  tiers {
    id
    name
    rank
    factionMatCombos {
      faction {
        id
        name
      }
      playerMat {
        id
        name
        abbrev
      }
      topPlayers(first: $numTopPlayers) {
        player {
          id
          displayName
          steamId
        }
        totalWins
      }
      totalWins
      totalMatches
      avgCoinsOnWin
      avgRoundsOnWin
      leastRoundsForWin
    }
  }
}
