query topPlayers($first: Int!, $after: String) {
  playersByWins(first: $first, after: $after) {
    edges {
      node {
        id
        displayName
        steamId
        totalWins
        totalMatches
      }
    }
  }
}
