FROM node:18.14.0 AS site-builder

COPY tsconfig.base.json .eslintignore .eslintrc.js package.json yarn.lock /app/
COPY ./site/package.json /app/site/package.json
COPY ./site/yarn.lock /app/site/yarn.lock

WORKDIR /app
RUN yarn && yarn install:site && yarn cache clean

COPY ./site /app/site

ENV NODE_ENV="production"
ENV NEXT_PUBLIC_WS_GRAPHQL_API_URL="wss://api.belovedpacifist.com/graphql"
ENV NEXT_PUBLIC_NODE_ENV="production"
ENV NEXT_PUBLIC_API_URL="https://api.belovedpacifist.com/"
ENV NEXT_PUBLIC_GRAPHQL_API_URL="https://api.belovedpacifist.com/graphql"
ENV NEXT_PUBLIC_GA_TRACKING_ID=""
ENV NEXT_PUBLIC_DISCORD_CLIENT_ID="715113915029389395"

RUN yarn build:site

FROM ubuntu/nginx:1.18-22.04_beta

RUN apt-get update && apt-get install -y \
  curl \
  && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash
RUN apt-get update && apt-get install -y \
  nodejs \
  dumb-init \
  && rm -rf /var/lib/apt/lists/*

RUN npm install --global yarn

COPY --from=site-builder /app/site /app/site

ENV NODE_ENV production
WORKDIR /app

CMD ["yarn", "--cwd", "site", "next", "start", "-p", "9000"]